# version: 2
# jobs:
#   build:
#     docker:
#       - image: circleci/python:3.7

#     working_directory: ~/repo

#     steps:
#       # Step 1: obtain repo from GitHub
#       - checkout
#       # Step 2: run linter and tests
#       - run:
#           name: run tests
#           command: |
#             python code.py





# version: 2
# jobs:
#  build:
#    docker:
#      - image: circleci/python:3.7

#    working_directory: ~/repo

#    steps:
#      # Step 1: obtain repo from GitHub
#      - checkout
#      # Step 2: create virtual env and install dependencies
#      - run:
#          name: install dependencies
#          command: |
#            sudo pip install pipenv
# 	         pipenv install

#      # Step 3: run linter and tests
#      - run:
#          name: run tests
#          command: |
#            pipenv run python code.py




version: 2.1

orbs:
  python: circleci/python@0.2.1

jobs:
  build:
    docker:
      - image: circleci/python:3.7

    working_directory: ~/repo

    steps:
      # Step 1: obtain repo from GitHub
      - checkout
      # Step 2: create virtual env and install dependencies
      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
      # Step 3: run linter and tests
      - run:
          name: run tests
          command: |
            . venv/bin/activate
            python code.py





