version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.7

    working_directory: ~/repo

    steps:
      # Step 1: obtain repo from GitHub
      - checkout
      # Step 2: create virtual env and install dependencies
      - run:
          name: install dependencies
          command: |
            sudo pip install pipenv
	    pyenv install 3.6.3
            pipenv install

      # Step 3: run linter and tests
      - run:
          name: run tests
          command: |
            pipenv run python code.py
