version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.7

    working_directory: ~/repo

    steps:
      # Step 1: obtain repo from GitHub
      - checkout
      # Step 2: run linter and tests
      - run:
          name: run tests
          command: |
            . citest/bin/activate
            python code.py
